project_id = "bvkcxmcwbwxguklimyym"

[functions.transcribe-audio]
verify_jwt = false

[functions.analyze-conversation]
verify_jwt = false

[functions.analyze-recording]
verify_jwt = false

[functions.salesforce-sync]
verify_jwt = false

[functions.generate-call-summary]
verify_jwt = false

[functions.salesforce-oauth]
verify_jwt = false
